version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: deposito-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: deposito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deposito-net

  backend:
    build: .
    container_name: deposito-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/deposito
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIEpXVC4uLg==
      MAIL_USER: ktrabajo870@gmail.com
      MAIL_PASSWORD: bhqu vpzu oxuy lntp
      ADMIN_EMAIL: kevinolarte.ko@gmail.com
      ADMIN_PASSWORD: 1234
      ADMIN_NAME: Kevin
    ports:
      - "8080:8080"
    networks:
      - deposito-net

volumes:
  postgres_data:

networks:
  deposito-net:
    driver: bridge
